import Head from "next/head";

export default function Home() {
  return (
    <div className="w-[100vw] h-[100vh] bg-cover bg-[url('/cover.png')] text-white -mt-[6em]">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="grid grid-cols-1 sm:grid-cols-[40em_1fr] h-[100vh] sm:pl-[10em] pt-[13em]">
        <div className="">
          <h1
            className="text-[2.54em] mt-[2em] sm:-mt-[0.5em] px-[0.5em] sm:px-[0.5em] sm:text-[4.7em] font-black leading-[1.2em] sm:leading-[1em]
              text-transparent bg-clip-text bg-gradient-to-br from-blue-300 to-green-300"
          >
            Blockchain Explorer, Analytics and Web services
          </h1>
          <p className="pt-[1em] px-[1em] text-[1.2em] sm:px-[1.9em]">
            Explore data stored on 7 blockchains. Blockchain information for
            Bitcoin (BTC) including historical prices, the most recently mined
            blocks, the mempool size of unconfirmed transactions, and data for
            the latest transactions.
          </p>
        </div>
      </main>
    </div>
  );
}
